export interface AgentPathInfo {
  project: string;
  global: string;
  displayName: string;
}

export const AGENT_PATHS: Record<string, AgentPathInfo> = {
  'aider-desk': {project: '.aider-desk/skills', global: '~/.aider-desk/skills', displayName: 'AiderDesk'},
  amp: {project: '.agents/skills', global: '~/.config/agents/skills', displayName: 'Amp'},
  replit: {project: '.agents/skills', global: '~/.config/agents/skills', displayName: 'Replit'},
  universal: {project: '.agents/skills', global: '~/.config/agents/skills', displayName: 'Universal'},
  antigravity: {project: '.agents/skills', global: '~/.gemini/antigravity/skills', displayName: 'Antigravity'},
  'antigravity-cli': {
    project: '.agents/skills',
    global: '~/.gemini/antigravity-cli/skills',
    displayName: 'Antigravity CLI',
  },
  astrbot: {project: 'data/skills', global: '~/.astrbot/data/skills', displayName: 'AstrBot'},
  'autohand-code': {project: '.autohand/skills', global: '~/.autohand/skills', displayName: 'Autohand Code CLI'},
  augment: {project: '.augment/skills', global: '~/.augment/skills', displayName: 'Augment'},
  bob: {project: '.bob/skills', global: '~/.bob/skills', displayName: 'IBM Bob'},
  'claude-code': {project: '.claude/skills', global: '~/.claude/skills', displayName: 'Claude Code'},
  openclaw: {project: 'skills', global: '~/.openclaw/skills', displayName: 'OpenClaw'},
  cline: {project: '.agents/skills', global: '~/.agents/skills', displayName: 'Cline'},
  dexto: {project: '.agents/skills', global: '~/.agents/skills', displayName: 'Dexto'},
  'kimi-code-cli': {project: '.agents/skills', global: '~/.agents/skills', displayName: 'Kimi Code CLI'},
  loaf: {project: '.agents/skills', global: '~/.agents/skills', displayName: 'Loaf'},
  warp: {project: '.agents/skills', global: '~/.agents/skills', displayName: 'Warp'},
  zed: {project: '.agents/skills', global: '~/.agents/skills', displayName: 'Zed'},
  'codearts-agent': {project: '.codeartsdoer/skills', global: '~/.codeartsdoer/skills', displayName: 'CodeArts Agent'},
  codebuddy: {project: '.codebuddy/skills', global: '~/.codebuddy/skills', displayName: 'CodeBuddy'},
  codemaker: {project: '.codemaker/skills', global: '~/.codemaker/skills', displayName: 'Codemaker'},
  codestudio: {project: '.codestudio/skills', global: '~/.codestudio/skills', displayName: 'Code Studio'},
  codex: {project: '.agents/skills', global: '~/.codex/skills', displayName: 'Codex'},
  'command-code': {project: '.commandcode/skills', global: '~/.commandcode/skills', displayName: 'Command Code'},
  continue: {project: '.continue/skills', global: '~/.continue/skills', displayName: 'Continue'},
  cortex: {project: '.cortex/skills', global: '~/.snowflake/cortex/skills', displayName: 'Cortex Code'},
  crush: {project: '.crush/skills', global: '~/.config/crush/skills', displayName: 'Crush'},
  cursor: {project: '.agents/skills', global: '~/.cursor/skills', displayName: 'Cursor'},
  deepagents: {project: '.agents/skills', global: '~/.deepagents/agent/skills', displayName: 'Deep Agents'},
  devin: {project: '.devin/skills', global: '~/.config/devin/skills', displayName: 'Devin for Terminal'},
  droid: {project: '.factory/skills', global: '~/.factory/skills', displayName: 'Droid'},
  eve: {project: 'agent/skills', global: '', displayName: 'Eve'},
  firebender: {project: '.agents/skills', global: '~/.firebender/skills', displayName: 'Firebender'},
  forgecode: {project: '.forge/skills', global: '~/.forge/skills', displayName: 'ForgeCode'},
  'gemini-cli': {project: '.agents/skills', global: '~/.gemini/skills', displayName: 'Gemini CLI'},
  'github-copilot': {project: '.agents/skills', global: '~/.copilot/skills', displayName: 'GitHub Copilot'},
  goose: {project: '.goose/skills', global: '~/.config/goose/skills', displayName: 'Goose'},
  'hermes-agent': {project: '.hermes/skills', global: '~/.hermes/skills', displayName: 'Hermes Agent'},
  'inference-sh': {project: '.inferencesh/skills', global: '~/.inferencesh/skills', displayName: 'inference.sh'},
  jazz: {project: '.jazz/skills', global: '~/.jazz/skills', displayName: 'Jazz'},
  junie: {project: '.junie/skills', global: '~/.junie/skills', displayName: 'Junie'},
  'iflow-cli': {project: '.iflow/skills', global: '~/.iflow/skills', displayName: 'iFlow CLI'},
  kilo: {project: '.kilocode/skills', global: '~/.kilocode/skills', displayName: 'Kilo Code'},
  'kiro-cli': {project: '.kiro/skills', global: '~/.kiro/skills', displayName: 'Kiro CLI'},
  kode: {project: '.kode/skills', global: '~/.kode/skills', displayName: 'Kode'},
  lingma: {project: '.lingma/skills', global: '~/.lingma/skills', displayName: 'Lingma'},
  mcpjam: {project: '.mcpjam/skills', global: '~/.mcpjam/skills', displayName: 'MCPJam'},
  'mistral-vibe': {project: '.vibe/skills', global: '~/.vibe/skills', displayName: 'Mistral Vibe'},
  moxby: {project: '.moxby/skills', global: '~/.moxby/skills', displayName: 'Moxby'},
  mux: {project: '.mux/skills', global: '~/.mux/skills', displayName: 'Mux'},
  opencode: {project: '.agents/skills', global: '~/.config/opencode/skills', displayName: 'OpenCode'},
  openhands: {project: '.openhands/skills', global: '~/.openhands/skills', displayName: 'OpenHands'},
  ona: {project: '.ona/skills', global: '~/.ona/skills', displayName: 'Ona'},
  pi: {project: '.pi/skills', global: '~/.pi/agent/skills', displayName: 'Pi'},
  qoder: {project: '.qoder/skills', global: '~/.qoder/skills', displayName: 'Qoder'},
  'qoder-cn': {project: '.qoder/skills', global: '~/.qoder-cn/skills', displayName: 'Qoder CN'},
  'qwen-code': {project: '.qwen/skills', global: '~/.qwen/skills', displayName: 'Qwen Code'},
  reasonix: {project: '.reasonix/skills', global: '~/.reasonix/skills', displayName: 'Reasonix'},
  rovodev: {project: '.rovodev/skills', global: '~/.rovodev/skills', displayName: 'Rovo Dev'},
  roo: {project: '.roo/skills', global: '~/.roo/skills', displayName: 'Roo Code'},
  'tabnine-cli': {project: '.tabnine/agent/skills', global: '~/.tabnine/agent/skills', displayName: 'Tabnine CLI'},
  terramind: {project: '.terramind/skills', global: '~/.terramind/skills', displayName: 'Terramind'},
  tinycloud: {project: '.tinycloud/skills', global: '~/.tinycloud/skills', displayName: 'Tinycloud'},
  trae: {project: '.trae/skills', global: '~/.trae/skills', displayName: 'Trae'},
  'trae-cn': {project: '.trae/skills', global: '~/.trae-cn/skills', displayName: 'Trae CN'},
  windsurf: {project: '.windsurf/skills', global: '~/.codeium/windsurf/skills', displayName: 'Windsurf'},
  zencoder: {project: '.zencoder/skills', global: '~/.zencoder/skills', displayName: 'Zencoder'},
  zenflow: {project: '.zencoder/skills', global: '~/.zencoder/skills', displayName: 'Zenflow'},
  neovate: {project: '.neovate/skills', global: '~/.neovate/skills', displayName: 'Neovate'},
  pochi: {project: '.pochi/skills', global: '~/.pochi/skills', displayName: 'Pochi'},
  promptscript: {project: '.agents/skills', global: '', displayName: 'PromptScript'},
  adal: {project: '.adal/skills', global: '~/.adal/skills', displayName: 'AdaL'},
};
